### ISSUE TITLE
Update gitignore to match gitignore.io

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#420]
# Question

There's a useful website that lists common gitignores -- for python: https://www.gitignore.io/api/python . Should we update to match this?

**Comment by matthewfeickert** [comment]
This seems to be a copy of [GitHub's Python gitignore file](https://github.com/github/gitignore/blob/master/Python.gitignore). 

There is some part of my brain that thinks @lukasheinrich and I had discussed this a very long time ago and we had thought that instead of just taking everything that is in that file that we would just build our own so that we intentionally ignore files. I don't know if this is true though, as I can't find an old Issue with this discussion.

I guess I would say that unless there is a super strong motivation to adopt it then we could just keep our own file, but I also don't have super strong feelings either way.
