### ISSUE TITLE
Test Deploy feature is broken

### ISSUE THREAD

**Issue by kratsg** [diana-hep/pyhf#432]
# Description

See https://github.com/FaradayRF/faradayio/issues/35 for a related issue - I think. Failing job on master here: https://travis-ci.org/diana-hep/pyhf/builds/517678508?utm_source=github_status&utm_medium=notification

# Expected Behavior

Expect it to pass.

# Actual Behavior

Observe it failing.

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
This is behaving as expected and isn't a bug. The PR was merged in before I had finished it.

**Comment by matthewfeickert** [comment]
ansible-lint is [able to do this properly](https://github.com/ansible/ansible-lint/blob/77fb2673dce4b9155f2ca532df8dc0d5a6c0b5d1/.travis.yml), but that's [apparently](https://twitter.com/webKnjaZ/status/1115641399117078529) because they use [`setuptools-scm`](https://github.com/ansible/ansible-lint/blob/77fb2673dce4b9155f2ca532df8dc0d5a6c0b5d1/setup.py#L7). I won't be able to get to this until tonight, so @kratsg if you have some PRs that you want to get done before then feel free to revert PR #429 (or just know that the last bit will error even if everything else is fine).

**Comment by matthewfeickert** [comment]
For sanity we may need to `++` in the next patch release we cut to `v0.0.18` (unless I'm making a mistake) as we are getting an scm tag of `v0.0.17.dev` tag from the `setuptools-scm` version. I'm not sure if this is because of the `binder` tag we have or something else. Will need to follow up more later.
