### ISSUE TITLE
make test-statistics tensor-aware

### ISSUE THREAD

**Issue by lukasheinrich** [diana-hep/pyhf#95]
# Description
 
we want to be able to do e.g. `tf.Session().run(qmu)`

**Comment by matthewfeickert** [comment]
As part of this, since in `runOnePoint()` `sqrtqmuA_v` will now be a tensor as a result of 

```python
sqrtqmuA_v = tensorlib.sqrt(qmuA_v)
```
then

```python
    sigma = muTest / sqrtqmuA_v if sqrtqmuA_v > 0 else None
```
will have to be tensorized, as tensors can not be used as `bools` in TensorFlow
```
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed.
```
As a result of this, I'm going to add tensorlib functions `greater` and `less` for the backends so that they can be safely used with `tensorlib.where`.

**Comment by matthewfeickert** [comment]
Relevant to PR #149, once I figure out how to get PyTorch v0.4 properly installed through Conda, is the ["Merging Tensor and Variable classes" section of the release notes](https://github.com/pytorch/pytorch/releases/tag/v0.4.0).

**Comment by matthewfeickert** [comment]
As a result of PR #149, can now do:
```python
>>> import pyhf
>>> import pyhf.simplemodels
>>> import tensorflow as tf
>>> pyhf.set_backend(pyhf.tensor.tensorflow_backend(session=tf.Session()))
>>> pdf = pyhf.simplemodels.hepdata_like([10.], [50.], [7.])
>>> data = [50.] + pdf.config.auxdata
>>> q_mu = pyhf.qmu(1.0, data, pdf, pdf.config.suggested_init(), pdf.config.suggested_bounds())
>>> q_mu
<tf.Tensor 'add_9:0' shape=(1,) dtype=float32>
>>> pyhf.tensorlib.session.run(q_mu)
array([1.0174799], dtype=float32)
```
